# This is a basic workflow to help you get started with Actions

name: New Relase

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
    inputs:
      tag:
        desription: Tag of the created release
        required: true
      modlist:
        description: The modpack's mod list
        required: true
        default: modlist.json

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2
  
      - name: Install From PyPI
        uses: BSFishy/pip-action@v1
        with:
          packages: requests

      # Runs a single command using the runners shell
      - name: Generate Manifest
        run: |
          cd $GITHUB_WORKSPACE/build
          ./createManifest.py ${{ github.event.inputs.tag }} $GITHUB_WORKSPACE/${{ github.event.inputs.modlist }}

